
rm(list=ls())
setwd("/home/dipesh/BA /Final Projects/Data /Linear Regression")

temp <- readxl::read_excel("/home/dipesh/BA /Final Projects/Data /Linear Regression Case.xlsx", sheet = "customer_dbase")
# Creating a Copy of the original file
getwd()
as.character(temp$region[temp$region==1]<-'Zone 1')
as.character(temp$region[temp$region==2]<-'Zone 2')
as.character(temp$region[temp$region==3]<-'Zone 3')
as.character(temp$region[temp$region==4]<-'Zone 4')
as.character(temp$region[temp$region==5]<-'Zone 5')
as.character(temp$townsize[temp$townsize==1]<-'> 250,000')
as.character(temp$townsize[temp$townsize==2]<-'50,000-249,999')
as.character(temp$townsize[temp$townsize==3]<-'10,000-49,999')
as.character(temp$townsize[temp$townsize==4]<-'2,500-9,999')
as.character(temp$townsize[temp$townsize==5]<-'< 2,500')
as.character(temp$gender[temp$gender==0]<-'Male')
as.character(temp$gender[temp$gender==1]<-'Female')
as.character(temp$agecat[temp$agecat==1]<-'<18')
as.character(temp$agecat[temp$agecat==2]<-'18-24')
as.character(temp$agecat[temp$agecat==3]<-'25-34')
as.character(temp$agecat[temp$agecat==4]<-'35-49')
as.character(temp$agecat[temp$agecat==5]<-'50-64')
as.character(temp$agecat[temp$agecat==6]<-'>65')
as.character(temp$agecat[temp$agecat==9]<-'No response')
as.character(temp$birthmonth[temp$birthmonth==4]<-'April')
as.character(temp$birthmonth[temp$birthmonth==8]<-'August')
as.character(temp$birthmonth[temp$birthmonth==12]<-'December')
as.character(temp$birthmonth[temp$birthmonth==2]<-'February')
as.character(temp$birthmonth[temp$birthmonth==1]<-'January')
as.character(temp$birthmonth[temp$birthmonth==7]<-'July')
as.character(temp$birthmonth[temp$birthmonth==6]<-'June')
as.character(temp$birthmonth[temp$birthmonth==3]<-'March')
as.character(temp$birthmonth[temp$birthmonth==5]<-'May')
as.character(temp$birthmonth[temp$birthmonth==11]<-'November')
as.character(temp$birthmonth[temp$birthmonth==10]<-'October')
as.character(temp$birthmonth[temp$birthmonth==9]<-'September')
as.character(temp$edcat[temp$edcat==1]<-'Did not complete high school')
as.character(temp$edcat[temp$edcat==2]<-'High school degree')
as.character(temp$edcat[temp$edcat==3]<-'Some college')
as.character(temp$edcat[temp$edcat==4]<-'College degree')
as.character(temp$edcat[temp$edcat==5]<-'Post-undergraduate degree')
as.character(temp$jobcat[temp$jobcat==1]<-'Managerial and Professional')
as.character(temp$jobcat[temp$jobcat==2]<-'Sales and Office')
as.character(temp$jobcat[temp$jobcat==3]<-'Service')
as.character(temp$jobcat[temp$jobcat==4]<-'Agricultural and Natural Resources')
as.character(temp$jobcat[temp$jobcat==5]<-'Precision Production, Craft, Repair')
as.character(temp$jobcat[temp$jobcat==6]<-'Operation, Fabrication, General Labor')
as.character(temp$union[temp$union==0]<-'No')
as.character(temp$union[temp$union==1]<-'Yes')
as.character(temp$employ[temp$employ==0]<-'0')
as.character(temp$employ[temp$employ==1]<-'1')
as.character(temp$employ[temp$employ==2]<-'2')
as.character(temp$employ[temp$employ==3]<-'3')
as.character(temp$employ[temp$employ==4]<-'4')
as.character(temp$employ[temp$employ==5]<-'5')
as.character(temp$employ[temp$employ==6]<-'6')
as.character(temp$employ[temp$employ==7]<-'7')
as.character(temp$employ[temp$employ==8]<-'8')
as.character(temp$employ[temp$employ==9]<-'9')
as.character(temp$employ[temp$employ==10]<-'10')
as.character(temp$employ[temp$employ==11]<-'11')
as.character(temp$employ[temp$employ==12]<-'12')
as.character(temp$employ[temp$employ==13]<-'13')
as.character(temp$employ[temp$employ==14]<-'14')
as.character(temp$employ[temp$employ==15]<-'15')
as.character(temp$employ[temp$employ==16]<-'16')
as.character(temp$employ[temp$employ==17]<-'17')
as.character(temp$employ[temp$employ==18]<-'18')
as.character(temp$employ[temp$employ==19]<-'19')
as.character(temp$employ[temp$employ==20]<-'20')
as.character(temp$employ[temp$employ==21]<-'21')
as.character(temp$employ[temp$employ==22]<-'22')
as.character(temp$employ[temp$employ==23]<-'23')
as.character(temp$employ[temp$employ==24]<-'24')
as.character(temp$employ[temp$employ==25]<-'25')
as.character(temp$employ[temp$employ==26]<-'26')
as.character(temp$employ[temp$employ==27]<-'27')
as.character(temp$employ[temp$employ==28]<-'28')
as.character(temp$employ[temp$employ==29]<-'29')
as.character(temp$employ[temp$employ==30]<-'30')
as.character(temp$employ[temp$employ==31]<-'31')
as.character(temp$employ[temp$employ==32]<-'32')
as.character(temp$employ[temp$employ==33]<-'33')
as.character(temp$employ[temp$employ==34]<-'34')
as.character(temp$employ[temp$employ==35]<-'35')
as.character(temp$employ[temp$employ==36]<-'36')
as.character(temp$employ[temp$employ==37]<-'37')
as.character(temp$employ[temp$employ==38]<-'38')
as.character(temp$employ[temp$employ==39]<-'39')
as.character(temp$employ[temp$employ==40]<-'40')
as.character(temp$employ[temp$employ==41]<-'41')
as.character(temp$employ[temp$employ==42]<-'42')
as.character(temp$employ[temp$employ==43]<-'43')
as.character(temp$employ[temp$employ==44]<-'44')
as.character(temp$employ[temp$employ==45]<-'45')
as.character(temp$employ[temp$employ==46]<-'46')
as.character(temp$employ[temp$employ==47]<-'47')
as.character(temp$employ[temp$employ==48]<-'48')
as.character(temp$employ[temp$employ==49]<-'49')
as.character(temp$employ[temp$employ==51]<-'51')
as.character(temp$employ[temp$employ==52]<-'52')
as.character(temp$empcat[temp$empcat==1]<-'Less than 2')
as.character(temp$empcat[temp$empcat==2]<-'2 to 5')
as.character(temp$empcat[temp$empcat==3]<-'6 to 10')
as.character(temp$empcat[temp$empcat==4]<-'11 to 15')
as.character(temp$empcat[temp$empcat==5]<-'More than 15')
as.character(temp$retire[temp$retire==0]<-'No')
as.character(temp$retire[temp$retire==1]<-'Yes')
as.character(temp$inccat[temp$inccat==1]<-'Under $25')
as.character(temp$inccat[temp$inccat==2]<-'$25 - $49')
as.character(temp$inccat[temp$inccat==3]<-'$50 - $74')
as.character(temp$inccat[temp$inccat==4]<-'$75 - $124')
as.character(temp$inccat[temp$inccat==5]<-'$125+')
as.character(temp$default[temp$default==0]<-'No')
as.character(temp$default[temp$default==1]<-'Yes')
as.character(temp$jobsat[temp$jobsat==1]<-'Highly dissatisfied')
as.character(temp$jobsat[temp$jobsat==2]<-'Somewhat dissatisfied')
as.character(temp$jobsat[temp$jobsat==3]<-'Neutral')
as.character(temp$jobsat[temp$jobsat==4]<-'Somewhat satisfied')
as.character(temp$jobsat[temp$jobsat==5]<-'Highly satisfied')
as.character(temp$marital[temp$marital==0]<-'Unmarried')
as.character(temp$marital[temp$marital==1]<-'Married')
as.character(temp$spousedcat[temp$spousedcat==-1]<-'Not married')
as.character(temp$spousedcat[temp$spousedcat==1]<-'Did not complete high school')
as.character(temp$spousedcat[temp$spousedcat==2]<-'High school degree')
as.character(temp$spousedcat[temp$spousedcat==3]<-'Some college')
as.character(temp$spousedcat[temp$spousedcat==4]<-'College degree')
as.character(temp$spousedcat[temp$spousedcat==5]<-'Post-undergraduate degree')
as.character(temp$homeown[temp$homeown==0]<-'Rent')
as.character(temp$homeown[temp$homeown==1]<-'Own')
as.character(temp$hometype[temp$hometype==1]<-'Single-family')
as.character(temp$hometype[temp$hometype==2]<-'Multiple-Family')
as.character(temp$hometype[temp$hometype==3]<-'Condominium/Townhouse')
as.character(temp$hometype[temp$hometype==4]<-'Mobile Home')
as.character(temp$address[temp$address==0]<-'0')
as.character(temp$address[temp$address==1]<-'1')
as.character(temp$address[temp$address==2]<-'2')
as.character(temp$address[temp$address==3]<-'3')
as.character(temp$address[temp$address==4]<-'4')
as.character(temp$address[temp$address==5]<-'5')
as.character(temp$address[temp$address==6]<-'6')
as.character(temp$address[temp$address==7]<-'7')
as.character(temp$address[temp$address==8]<-'8')
as.character(temp$address[temp$address==9]<-'9')
as.character(temp$address[temp$address==10]<-'10')
as.character(temp$address[temp$address==11]<-'11')
as.character(temp$address[temp$address==12]<-'12')
as.character(temp$address[temp$address==13]<-'13')
as.character(temp$address[temp$address==14]<-'14')
as.character(temp$address[temp$address==15]<-'15')
as.character(temp$address[temp$address==16]<-'16')
as.character(temp$address[temp$address==17]<-'17')
as.character(temp$address[temp$address==18]<-'18')
as.character(temp$address[temp$address==19]<-'19')
as.character(temp$address[temp$address==20]<-'20')
as.character(temp$address[temp$address==21]<-'21')
as.character(temp$address[temp$address==22]<-'22')
as.character(temp$address[temp$address==23]<-'23')
as.character(temp$address[temp$address==24]<-'24')
as.character(temp$address[temp$address==25]<-'25')
as.character(temp$address[temp$address==26]<-'26')
as.character(temp$address[temp$address==27]<-'27')
as.character(temp$address[temp$address==28]<-'28')
as.character(temp$address[temp$address==29]<-'29')
as.character(temp$address[temp$address==30]<-'30')
as.character(temp$address[temp$address==31]<-'31')
as.character(temp$address[temp$address==32]<-'32')
as.character(temp$address[temp$address==33]<-'33')
as.character(temp$address[temp$address==34]<-'34')
as.character(temp$address[temp$address==35]<-'35')
as.character(temp$address[temp$address==36]<-'36')
as.character(temp$address[temp$address==37]<-'37')
as.character(temp$address[temp$address==38]<-'38')
as.character(temp$address[temp$address==39]<-'39')
as.character(temp$address[temp$address==40]<-'40')
as.character(temp$address[temp$address==41]<-'41')
as.character(temp$address[temp$address==42]<-'42')
as.character(temp$address[temp$address==43]<-'43')
as.character(temp$address[temp$address==44]<-'44')
as.character(temp$address[temp$address==45]<-'45')
as.character(temp$address[temp$address==46]<-'46')
as.character(temp$address[temp$address==47]<-'47')
as.character(temp$address[temp$address==48]<-'48')
as.character(temp$address[temp$address==49]<-'49')
as.character(temp$address[temp$address==50]<-'50')
as.character(temp$address[temp$address==51]<-'51')
as.character(temp$address[temp$address==52]<-'52')
as.character(temp$address[temp$address==53]<-'53')
as.character(temp$address[temp$address==54]<-'54')
as.character(temp$address[temp$address==55]<-'55')
as.character(temp$address[temp$address==57]<-'57')
as.character(temp$addresscat[temp$addresscat==1]<-'Less than 3')
as.character(temp$addresscat[temp$addresscat==2]<-'4 to 7')
as.character(temp$addresscat[temp$addresscat==3]<-'8 to 15')
as.character(temp$addresscat[temp$addresscat==4]<-'16 to 25')
as.character(temp$addresscat[temp$addresscat==5]<-'More than 25')
as.character(temp$cars[temp$cars==0]<-'0')
as.character(temp$cars[temp$cars==1]<-'1')
as.character(temp$cars[temp$cars==2]<-'2')
as.character(temp$cars[temp$cars==3]<-'3')
as.character(temp$cars[temp$cars==4]<-'4')
as.character(temp$cars[temp$cars==5]<-'5')
as.character(temp$cars[temp$cars==6]<-'6')
as.character(temp$cars[temp$cars==7]<-'7')
as.character(temp$cars[temp$cars==8]<-'8')
as.character(temp$carown[temp$carown==-1]<-'N/A')
as.character(temp$carown[temp$carown==0]<-'Lease')
as.character(temp$carown[temp$carown==1]<-'Own')
as.character(temp$cartype[temp$cartype==-1]<-'N/A')
as.character(temp$cartype[temp$cartype==0]<-'Domestic')
as.character(temp$cartype[temp$cartype==1]<-'Import')
as.character(temp$carcatvalue[temp$carcatvalue==-1]<-'N/A')
as.character(temp$carcatvalue[temp$carcatvalue==1]<-'Economy')
as.character(temp$carcatvalue[temp$carcatvalue==2]<-'Standard')
as.character(temp$carcatvalue[temp$carcatvalue==3]<-'Luxury')
as.character(temp$carbought[temp$carbought==-1]<-'N/A')
as.character(temp$carbought[temp$carbought==0]<-'No')
as.character(temp$carbought[temp$carbought==1]<-'Yes')
as.character(temp$carbuy[temp$carbuy==0]<-'No')
as.character(temp$carbuy[temp$carbuy==1]<-'Yes')
as.character(temp$commute[temp$commute==1]<-'Car')
as.character(temp$commute[temp$commute==2]<-'Motorcycle')
as.character(temp$commute[temp$commute==3]<-'Carpool')
as.character(temp$commute[temp$commute==4]<-'Bus')
as.character(temp$commute[temp$commute==5]<-'Train/Subway')
as.character(temp$commute[temp$commute==6]<-'Other public transit')
as.character(temp$commute[temp$commute==7]<-'Bicycle')
as.character(temp$commute[temp$commute==8]<-'Walk')
as.character(temp$commute[temp$commute==9]<-'Other non-motorized transit')
as.character(temp$commute[temp$commute==10]<-'Telecommute')
as.character(temp$commutecat[temp$commutecat==1]<-'Single occupancy')
as.character(temp$commutecat[temp$commutecat==2]<-'Multiple occupancy')
as.character(temp$commutecat[temp$commutecat==3]<-'Public transportation')
as.character(temp$commutecat[temp$commutecat==4]<-'Non-motorized')
as.character(temp$commutecat[temp$commutecat==5]<-'Telecommute')
as.character(temp$commutecar[temp$commutecar==0]<-'No')
as.character(temp$commutecar[temp$commutecar==1]<-'Yes')
as.character(temp$commutemotorcycle[temp$commutemotorcycle==0]<-'No')
as.character(temp$commutemotorcycle[temp$commutemotorcycle==1]<-'Yes')
as.character(temp$commutecarpool[temp$commutecarpool==0]<-'No')
as.character(temp$commutecarpool[temp$commutecarpool==1]<-'Yes')
as.character(temp$commutebus[temp$commutebus==0]<-'No')
as.character(temp$commutebus[temp$commutebus==1]<-'Yes')
as.character(temp$commuterail[temp$commuterail==0]<-'No')
as.character(temp$commuterail[temp$commuterail==1]<-'Yes')
as.character(temp$commutepublic[temp$commutepublic==0]<-'No')
as.character(temp$commutepublic[temp$commutepublic==1]<-'Yes')
as.character(temp$commmutebike[temp$commmutebike==0]<-'No')
as.character(temp$commmutebike[temp$commmutebike==1]<-'Yes')
as.character(temp$commutewalk[temp$commutewalk==0]<-'No')
as.character(temp$commutewalk[temp$commutewalk==1]<-'Yes')
as.character(temp$commuteonmotor[temp$commuteonmotor==0]<-'No')
as.character(temp$commuteonmotor[temp$commuteonmotor==1]<-'Yes')
as.character(temp$telecommute[temp$telecommute==0]<-'No')
as.character(temp$telecommute[temp$telecommute==1]<-'Yes')
as.character(temp$reason[temp$reason==1]<-'Prices')
as.character(temp$reason[temp$reason==2]<-'Convenience')
as.character(temp$reason[temp$reason==3]<-'Service')
as.character(temp$reason[temp$reason==4]<-'Other')
as.character(temp$reason[temp$reason==8]<-'N/A')
as.character(temp$reason[temp$reason==9]<-'No response')
as.character(temp$polview[temp$polview==1]<-'Extremely liberal')
as.character(temp$polview[temp$polview==2]<-'Liberal')
as.character(temp$polview[temp$polview==3]<-'Slightly liberal')
as.character(temp$polview[temp$polview==4]<-'Moderate')
as.character(temp$polview[temp$polview==5]<-'Slightly conservative')
as.character(temp$polview[temp$polview==6]<-'Conservative')
as.character(temp$polview[temp$polview==7]<-'Extremely conservative')
as.character(temp$polparty[temp$polparty==0]<-'No')
as.character(temp$polparty[temp$polparty==1]<-'Yes')
as.character(temp$polcontrib[temp$polcontrib==0]<-'No')
as.character(temp$polcontrib[temp$polcontrib==1]<-'Yes')
as.character(temp$vote[temp$vote==0]<-'No')
as.character(temp$vote[temp$vote==1]<-'Yes')
as.character(temp$card[temp$card==1]<-'American Express')
as.character(temp$card[temp$card==2]<-'Visa')
as.character(temp$card[temp$card==3]<-'Mastercard')
as.character(temp$card[temp$card==4]<-'Discover')
as.character(temp$card[temp$card==5]<-'Other')
as.character(temp$cardtype[temp$cardtype==1]<-'None')
as.character(temp$cardtype[temp$cardtype==2]<-'Gold')
as.character(temp$cardtype[temp$cardtype==3]<-'Platinum')
as.character(temp$cardtype[temp$cardtype==4]<-'Other')
as.character(temp$cardbenefit[temp$cardbenefit==1]<-'None')
as.character(temp$cardbenefit[temp$cardbenefit==2]<-'Cash back')
as.character(temp$cardbenefit[temp$cardbenefit==3]<-'Airline miles')
as.character(temp$cardbenefit[temp$cardbenefit==4]<-'Other')
as.character(temp$cardfee[temp$cardfee==0]<-'No')
as.character(temp$cardfee[temp$cardfee==1]<-'Yes')
as.character(temp$cardtenure[temp$cardtenure==0]<-'0')
as.character(temp$cardtenure[temp$cardtenure==1]<-'1')
as.character(temp$cardtenure[temp$cardtenure==2]<-'2')
as.character(temp$cardtenure[temp$cardtenure==3]<-'3')
as.character(temp$cardtenure[temp$cardtenure==4]<-'4')
as.character(temp$cardtenure[temp$cardtenure==5]<-'5')
as.character(temp$cardtenure[temp$cardtenure==6]<-'6')
as.character(temp$cardtenure[temp$cardtenure==7]<-'7')
as.character(temp$cardtenure[temp$cardtenure==8]<-'8')
as.character(temp$cardtenure[temp$cardtenure==9]<-'9')
as.character(temp$cardtenure[temp$cardtenure==10]<-'10')
as.character(temp$cardtenure[temp$cardtenure==11]<-'11')
as.character(temp$cardtenure[temp$cardtenure==12]<-'12')
as.character(temp$cardtenure[temp$cardtenure==13]<-'13')
as.character(temp$cardtenure[temp$cardtenure==14]<-'14')
as.character(temp$cardtenure[temp$cardtenure==15]<-'15')
as.character(temp$cardtenure[temp$cardtenure==16]<-'16')
as.character(temp$cardtenure[temp$cardtenure==17]<-'17')
as.character(temp$cardtenure[temp$cardtenure==18]<-'18')
as.character(temp$cardtenure[temp$cardtenure==19]<-'19')
as.character(temp$cardtenure[temp$cardtenure==20]<-'20')
as.character(temp$cardtenure[temp$cardtenure==21]<-'21')
as.character(temp$cardtenure[temp$cardtenure==22]<-'22')
as.character(temp$cardtenure[temp$cardtenure==23]<-'23')
as.character(temp$cardtenure[temp$cardtenure==24]<-'24')
as.character(temp$cardtenure[temp$cardtenure==25]<-'25')
as.character(temp$cardtenure[temp$cardtenure==26]<-'26')
as.character(temp$cardtenure[temp$cardtenure==27]<-'27')
as.character(temp$cardtenure[temp$cardtenure==28]<-'28')
as.character(temp$cardtenure[temp$cardtenure==29]<-'29')
as.character(temp$cardtenure[temp$cardtenure==30]<-'30')
as.character(temp$cardtenure[temp$cardtenure==31]<-'31')
as.character(temp$cardtenure[temp$cardtenure==32]<-'32')
as.character(temp$cardtenure[temp$cardtenure==33]<-'33')
as.character(temp$cardtenure[temp$cardtenure==34]<-'34')
as.character(temp$cardtenure[temp$cardtenure==35]<-'35')
as.character(temp$cardtenure[temp$cardtenure==36]<-'36')
as.character(temp$cardtenure[temp$cardtenure==37]<-'37')
as.character(temp$cardtenure[temp$cardtenure==38]<-'38')
as.character(temp$cardtenure[temp$cardtenure==39]<-'39')
as.character(temp$cardtenure[temp$cardtenure==40]<-'40')
as.character(temp$cardtenutrecat[temp$cardtenutrecat==1]<-'Less than 2')
as.character(temp$cardtenutrecat[temp$cardtenutrecat==2]<-'2 to 5')
as.character(temp$cardtenutrecat[temp$cardtenutrecat==3]<-'6 to 10')
as.character(temp$cardtenutrecat[temp$cardtenutrecat==4]<-'11 to 15')
as.character(temp$cardtenutrecat[temp$cardtenutrecat==5]<-'More than 15')
as.character(temp$card2[temp$card2==1]<-'American Express')
as.character(temp$card2[temp$card2==2]<-'Visa')
as.character(temp$card2[temp$card2==3]<-'Mastercard')
as.character(temp$card2[temp$card2==4]<-'Discover')
as.character(temp$card2[temp$card2==5]<-'Other')
as.character(temp$card2type[temp$card2type==1]<-'None')
as.character(temp$card2type[temp$card2type==2]<-'Gold')
as.character(temp$card2type[temp$card2type==3]<-'Platinum')
as.character(temp$card2type[temp$card2type==4]<-'Other')
as.character(temp$card2type[temp$card2type==1]<-'None')
as.character(temp$card2benefit[temp$card2benefit==2]<-'Cash back')
as.character(temp$card2benefit[temp$card2benefit==3]<-'Airline miles')
as.character(temp$card2benefit[temp$card2benefit==4]<-'Other')
as.character(temp$card2fee[temp$card2fee==0]<-'No')
as.character(temp$card2fee[temp$card2fee==1]<-'Yes')
as.character(temp$card2tenure[temp$card2tenure==0]<-'0')
as.character(temp$card2tenure[temp$card2tenure==1]<-'1')
as.character(temp$card2tenure[temp$card2tenure==2]<-'2')
as.character(temp$card2tenure[temp$card2tenure==3]<-'3')
as.character(temp$card2tenure[temp$card2tenure==4]<-'4')
as.character(temp$card2tenure[temp$card2tenure==5]<-'5')
as.character(temp$card2tenure[temp$card2tenure==6]<-'6')
as.character(temp$card2tenure[temp$card2tenure==7]<-'7')
as.character(temp$card2tenure[temp$card2tenure==8]<-'8')
as.character(temp$card2tenure[temp$card2tenure==9]<-'9')
as.character(temp$card2tenure[temp$card2tenure==10]<-'10')
as.character(temp$card2tenure[temp$card2tenure==11]<-'11')
as.character(temp$card2tenure[temp$card2tenure==12]<-'12')
as.character(temp$card2tenure[temp$card2tenure==13]<-'13')
as.character(temp$card2tenure[temp$card2tenure==14]<-'14')
as.character(temp$card2tenure[temp$card2tenure==15]<-'15')
as.character(temp$card2tenure[temp$card2tenure==16]<-'16')
as.character(temp$card2tenure[temp$card2tenure==17]<-'17')
as.character(temp$card2tenure[temp$card2tenure==18]<-'18')
as.character(temp$card2tenure[temp$card2tenure==19]<-'19')
as.character(temp$card2tenure[temp$card2tenure==20]<-'20')
as.character(temp$card2tenure[temp$card2tenure==21]<-'21')
as.character(temp$card2tenure[temp$card2tenure==22]<-'22')
as.character(temp$card2tenure[temp$card2tenure==23]<-'23')
as.character(temp$card2tenure[temp$card2tenure==24]<-'24')
as.character(temp$card2tenure[temp$card2tenure==25]<-'25')
as.character(temp$card2tenure[temp$card2tenure==26]<-'26')
as.character(temp$card2tenure[temp$card2tenure==27]<-'27')
as.character(temp$card2tenure[temp$card2tenure==28]<-'28')
as.character(temp$card2tenure[temp$card2tenure==29]<-'29')
as.character(temp$card2tenure[temp$card2tenure==30]<-'30')
as.character(temp$card2tenurecat[temp$card2tenurecat==1]<-'Less than 2')
as.character(temp$card2tenurecat[temp$card2tenurecat==2]<-'2 to 5')
as.character(temp$card2tenurecat[temp$card2tenurecat==3]<-'6 to 10')
as.character(temp$card2tenurecat[temp$card2tenurecat==4]<-'11 to 15')
as.character(temp$card2tenurecat[temp$card2tenurecat==5]<-'More than 15')
as.character(temp$active[temp$active==0]<-'No')
as.character(temp$active[temp$active==1]<-'Yes')
as.character(temp$bfast[temp$bfast==1]<-'Energy bar')
as.character(temp$bfast[temp$bfast==2]<-'Oatmeal')
as.character(temp$bfast[temp$bfast==3]<-'Cereal')
as.character(temp$churn[temp$churn==0]<-'No')
as.character(temp$churn[temp$churn==1]<-'Yes')
as.character(temp$tolfree[temp$tolfree==0]<-'No')
as.character(temp$tolfree[temp$tolfree==1]<-'Yes')
as.character(temp$equip[temp$equip==0]<-'No')
as.character(temp$equip[temp$equip==1]<-'Yes')
as.character(temp$callcard[temp$callcard==0]<-'No')
as.character(temp$callcard[temp$callcard==1]<-'Yes')
as.character(temp$wireless[temp$wireless==0]<-'No')
as.character(temp$wireless[temp$wireless==1]<-'Yes')
as.character(temp$multiline[temp$multiline==0]<-'No')
as.character(temp$multiline[temp$multiline==1]<-'Yes')
as.character(temp$voice[temp$voice==0]<-'No')
as.character(temp$voice[temp$voice==1]<-'Yes')
as.character(temp$pager[temp$pager==0]<-'No')
as.character(temp$pager[temp$pager==1]<-'Yes')
as.character(temp$internet[temp$internet==0]<-'None')
as.character(temp$internet[temp$internet==1]<-'Dial-up')
as.character(temp$internet[temp$internet==2]<-'DSL')
as.character(temp$internet[temp$internet==3]<-'Cable modem')
as.character(temp$internet[temp$internet==4]<-'Other')
as.character(temp$callid[temp$callid==0]<-'No')
as.character(temp$callid[temp$callid==1]<-'Yes')
as.character(temp$callwait[temp$callwait==0]<-'No')
as.character(temp$callwait[temp$callwait==1]<-'Yes')
as.character(temp$forward[temp$forward==0]<-'No')
as.character(temp$forward[temp$forward==1]<-'Yes')
as.character(temp$confer[temp$confer==0]<-'No')
as.character(temp$confer[temp$confer==1]<-'Yes')
as.character(temp$ebill[temp$ebill==0]<-'No')
as.character(temp$ebill[temp$ebill==1]<-'Yes')
as.character(temp$owntv[temp$owntv==0]<-'No')
as.character(temp$owntv[temp$owntv==1]<-'Yes')
as.character(temp$ownvcr[temp$ownvcr==0]<-'No')
as.character(temp$ownvcr[temp$ownvcr==1]<-'Yes')
as.character(temp$owndvd[temp$owndvd==0]<-'No')
as.character(temp$owndvd[temp$owndvd==1]<-'Yes')
as.character(temp$owncd[temp$owncd==0]<-'No')
as.character(temp$owncd[temp$owncd==1]<-'Yes')
as.character(temp$ownpda[temp$ownpda==0]<-'No')
as.character(temp$ownpda[temp$ownpda==1]<-'Yes')
as.character(temp$ownpc[temp$ownpc==0]<-'No')
as.character(temp$ownpc[temp$ownpc==1]<-'Yes')
as.character(temp$ownipod[temp$ownipod==0]<-'No')
as.character(temp$ownipod[temp$ownipod==1]<-'Yes')
as.character(temp$owngame[temp$owngame==0]<-'No')
as.character(temp$owngame[temp$owngame==1]<-'Yes')
as.character(temp$ownfax[temp$ownfax==0]<-'No')
as.character(temp$ownfax[temp$ownfax==1]<-'Yes')
as.character(temp$news[temp$news==0]<-'No')
as.character(temp$news[temp$news==1]<-'Yes')
as.character(temp$response_01[temp$response_01==0]<-'No')
as.character(temp$response_02[temp$response_02==1]<-'Yes')
as.character(temp$response_02[temp$response_02==0]<-'No')
as.character(temp$response_03[temp$response_03==1]<-'Yes')
as.character(temp$response_03[temp$response_03==0]<-'No')
as.character(temp$response_04[temp$response_04==1]<-'Yes')

table(temp)
summary(temp)
summary(temp$commutecat)
table(temp$commutecat)

write.csv(temp,"file_changed.csv")


